version: '3'

services:
  buildnumber:
    image: baibai/buildnumber
    container_name: buildnumber
    networks:
      - proxy
    volumes:
     - data:/data
    environment:
     - STORAGE_DIR=/data
     - PORT=8081
    restart: always
    labels:
      traefik.backend: "buildnumber"
      traefik.frontend.rule: $BUILDNUMBER_RULE
      traefik.port: 8081
      traefik.enable: true
      traefik.docker.network: "proxy"

volumes:
  data:

networks:
  proxy:
    external: true
